---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        nodeLabelsInherited: topology.kubernetes.io/region, topology.kubernetes.io/zone
      labels:
        nodeLabelInheritence: "enabled"
        app: nginx
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: nginx
      containers:
      - name: nginx
        image: nginx:latest
