kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    topology.kubernetes.io/region: us-nowhere-1
    topology.kubernetes.io/zone: us-nowhere-1a
- role: worker
  labels:
    topology.kubernetes.io/region: us-nowhere-1
    topology.kubernetes.io/zone: us-nowhere-1b
- role: worker
  labels:
    topology.kubernetes.io/region: us-nowhere-1
    topology.kubernetes.io/zone: us-nowhere-1c
