name: Helm chart

on:
  push:
    branches:
    - master
    paths:
    - chart/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CHART_LOCATION: ${{ github.repository_owner }}/charts

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  helm-new-version:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.old-version.outputs.version }}
      new-version: ${{ steps.new-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find new version
        id: new-version
        run: |
          NEW_VERSION=$(yq e '.version' chart/Chart.yaml)
          echo "version=${NEW_VERSION}" | tee -a $GITHUB_OUTPUT
      - name: Find old version
        id: old-version
        run: |
          git checkout ${{ github.event.pull_request.base.sha || github.event.before }}
          OLD_VERSION=$(yq e '.version' chart/Chart.yaml)
          echo "version=${OLD_VERSION}" | tee -a $GITHUB_OUTPUT

  helm-release:
    runs-on: ubuntu-latest
    needs: helm-new-version
    if: (github.event_name == 'push' && needs.helm-new-version.outputs.old-version != needs.helm-new-version.outputs.new-version) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - name: Find new version
        id: new_version
        run: |
          NEW_VERSION=$(yq e '.version' chart/Chart.yaml)
          echo "version=${NEW_VERSION}" | tee -a $GITHUB_OUTPUT
      - name: Generate new chart
        run: |
          helm package chart --dependency-update --destination packaged-helm-chart
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish chart as an OCI image
        run: |
          helm push packaged-helm-chart/*-${{ steps.new_version.outputs.version }}.tgz oci://${{ env.REGISTRY }}/${{ env.CHART_LOCATION }}
